# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel-Edge-Software
# This file is licensed under the Limited Edge Software Distribution License Agreement.

{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  annotations:
{{- range $key, $value := .Values.ingress.annotations }}
{{ $key | indent 4 }}: {{ $value | quote }}
{{- end }}
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: web
            port:
              number: 80
#      - pathType: Prefix
#        path: /mqtt
#        backend:
#          service:
#            name: broker
#            port:
#              number: 1884
{{- if ne (default .Values.ingress.className "") "" }}
  ingressClassName: {{ .Values.ingress.className }}
{{- end }}
{{- end }}
