# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel-Edge-Software
# This file is licensed under the Limited Edge Software Distribution License Agreement.

apiVersion: v2
name: scenescape-chart
description: A Helm chart for SceneScape
type: application
version: 1.2.0
appVersion: "1.3.0"
